### ISSUE TITLE
ViewPagerEx.java line 1852

### ISSUE THREAD

**Issue by bymoud** [daimajia/AndroidImageSlider#149]
I started using the latest version of your library, and when I launched my app into production, Crashlytics have been reporting the following issue multiple times.

`java.lang.IllegalArgumentException: pointerIndex out of range
       at android.view.MotionEvent.nativeGetAxisValue(MotionEvent.java)
       at android.view.MotionEvent.getX(MotionEvent.java:2106)
       at android.support.v4.view.MotionEventCompatEclair.getX(MotionEventCompatEclair.java:32)
       at android.support.v4.view.MotionEventCompat$EclairMotionEventVersionImpl.getX(MotionEventCompat.java:110)
       at android.support.v4.view.MotionEventCompat.getX(MotionEventCompat.java:462)
       at com.daimajia.slider.library.Tricks.ViewPagerEx.onInterceptTouchEvent(ViewPagerEx.java:1852)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2285)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2684)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2400)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2684)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2400)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2684)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2400)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2684)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2400)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2684)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2400)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2684)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2400)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2684)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2400)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2684)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2400)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2552)
       at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1767)
       at android.app.Activity.dispatchTouchEvent(Activity.java:2840)
       at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2513)
       at android.view.View.dispatchPointerEvent(View.java:9125)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4632)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4470)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4020)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4073)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4039)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4153)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4047)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4210)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4020)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4073)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4039)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4047)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4020)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6480)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6379)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6350)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6570)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:143)
       at android.os.Looper.loop(Looper.java:130)
       at android.app.ActivityThread.main(ActivityThread.java:5832)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)`

**Comment by tamtom** [comment]
any update?

**Comment by SalvatoreAD** [comment]
i have same issue
