### ISSUE TITLE
The specified child already has a parent. You must call removeView() on the child's parent first.

### ISSUE THREAD

**Issue by giangqaz** [daimajia/AndroidImageSlider#150]
I have this problem when try to add slider view when I paser data from internet
but it is fine when I create dummy data from code.
Anyone know about this problem?
thanks
[Update] I try using timertask to check this and result is same.
<code>
Timer timer = new Timer();
        TimerTask tt = new TimerTask() {
            @Override
            public void run() {
                runOnUiThread(new Runnable() {
                    @Override
                    public void run() {
                        addSliderShow();
                    }
                });
            }
        };
</code>

here is exception

<code> 
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
            at android.view.ViewGroup.addViewInner(ViewGroup.java:3593)
            at android.view.ViewGroup.addView(ViewGroup.java:3446)
            at com.daimajia.slider.library.Tricks.ViewPagerEx.addView(ViewPagerEx.java:1321)
            at android.view.ViewGroup.addView(ViewGroup.java:3391)
            at android.view.ViewGroup.addView(ViewGroup.java:3367)
            at com.daimajia.slider.library.SliderAdapter.instantiateItem(SliderAdapter.java:82)
            at com.daimajia.slider.library.Tricks.InfinitePagerAdapter.instantiateItem(InfinitePagerAdapter.java:54)
            at com.daimajia.slider.library.Tricks.ViewPagerEx.addNewItem(ViewPagerEx.java:848)
            at com.daimajia.slider.library.Tricks.ViewPagerEx.populate(ViewPagerEx.java:1032)
            at com.daimajia.slider.library.Tricks.ViewPagerEx.setCurrentItemInternal(ViewPagerEx.java:562)
            at com.daimajia.slider.library.Tricks.ViewPagerEx.setCurrentItemInternal(ViewPagerEx.java:526)
            at com.daimajia.slider.library.Tricks.ViewPagerEx.setCurrentItem(ViewPagerEx.java:507)
            at com.daimajia.slider.library.Indicators.PagerIndicator$1.onChanged(PagerIndicator.java:411)
            at android.database.DataSetObservable.notifyChanged(DataSetObservable.java:37)
            at android.support.v4.view.PagerAdapter.notifyDataSetChanged(PagerAdapter.java:276)
            at com.daimajia.slider.library.SliderAdapter.addSlider(SliderAdapter.java:28)
            at com.daimajia.slider.library.SliderLayout.addSlider(SliderLayout.java:237)
</code>

**Comment by superhyn** [comment]
i have the same problem with you,plz tell me how can i solve this issue

**Comment by JackyKeke** [comment]
感谢你的来信，我会及时处理。祝工作顺利，万事如意
