### ISSUE TITLE
Out of memory 

### ISSUE THREAD

**Issue by thair-jaber** [daimajia/AndroidImageSlider#215]
Dears,

I'm getting this error , and this cause the image not to be shown ,can you help me finding what's i'm doing wrong :
E/dalvikvm-heap: Out of memory on a 7970416-byte allocation.
 "Picasso-/Content/UploadedImages/IMG-20160322-WA0021.jpg" prio=5 tid=31 RUNNABLE
  | group="main" sCount=0 dsCount=0 obj=0x434dbe68 self=0x78389a58
  | sysTid=19767 nice=10 sched=0/0 cgrp=apps/bg_non_interactive handle=2024977608
  | state=R schedstat=( 0 0 0 ) utm=76 stm=7 core=3
    at android.graphics.Bitmap.nativeCreate(Native Method)
  at android.graphics.Bitmap.createBitmap(Bitmap.java:903)
   at android.graphics.Bitmap.createBitmap(Bitmap.java:880)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:812)
   at com.squareup.picasso.BitmapHunter.transformResult(BitmapHunter.java:457)
  at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:154)
  at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:101)
   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
   at java.lang.Thread.run(Thread.java:841)
   at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:394)

**Comment by fedek6** [comment]
I have the same problem when sliding really fast.
