### ISSUE TITLE
Corrupt XML binary file

### ISSUE THREAD

**Issue by hydrated** [daimajia/AndroidImageSlider#327]
Recently we got one crash report below.

Happen chance is really rare.

```
Fatal Exception: android.view.InflateException: Corrupt XML binary file
       at android.view.LayoutInflater.inflate(LayoutInflater.java:523)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
       at com.daimajia.slider.library.SliderTypes.DefaultSliderView.getView(DefaultSliderView.java:23)
       at com.daimajia.slider.library.SliderAdapter.instantiateItem(SliderAdapter.java:81)
       at com.daimajia.slider.library.Tricks.InfinitePagerAdapter.instantiateItem(InfinitePagerAdapter.java:54)
       at com.daimajia.slider.library.Tricks.ViewPagerEx.addNewItem(ViewPagerEx.java:848)
       at com.daimajia.slider.library.Tricks.ViewPagerEx.populate(ViewPagerEx.java:1064)
       at com.daimajia.slider.library.Tricks.ViewPagerEx.setCurrentItemInternal(ViewPagerEx.java:562)
       at com.daimajia.slider.library.Tricks.ViewPagerEx.setCurrentItemInternal(ViewPagerEx.java:526)
       at com.daimajia.slider.library.Tricks.ViewPagerEx.setCurrentItem(ViewPagerEx.java:518)
       at com.daimajia.slider.library.SliderLayout.moveNextPosition(SliderLayout.java:696)
       at com.daimajia.slider.library.SliderLayout$2.handleMessage(SliderLayout.java:244)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:6102)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
Caused by org.xmlpull.v1.XmlPullParserException: Corrupt XML binary file
       at android.content.res.XmlBlock.nativeNext(XmlBlock.java)
       at android.content.res.XmlBlock$Parser.next(XmlBlock.java:244)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:454)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
       at com.daimajia.slider.library.SliderTypes.DefaultSliderView.getView(DefaultSliderView.java:23)
       at com.daimajia.slider.library.SliderAdapter.instantiateItem(SliderAdapter.java:81)
       at com.daimajia.slider.library.Tricks.InfinitePagerAdapter.instantiateItem(InfinitePagerAdapter.java:54)
       at com.daimajia.slider.library.Tricks.ViewPagerEx.addNewItem(ViewPagerEx.java:848)
       at com.daimajia.slider.library.Tricks.ViewPagerEx.populate(ViewPagerEx.java:1064)
       at com.daimajia.slider.library.Tricks.ViewPagerEx.setCurrentItemInternal(ViewPagerEx.java:562)
       at com.daimajia.slider.library.Tricks.ViewPagerEx.setCurrentItemInternal(ViewPagerEx.java:526)
       at com.daimajia.slider.library.Tricks.ViewPagerEx.setCurrentItem(ViewPagerEx.java:518)
       at com.daimajia.slider.library.SliderLayout.moveNextPosition(SliderLayout.java:696)
       at com.daimajia.slider.library.SliderLayout$2.handleMessage(SliderLayout.java:244)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:6102)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
```

**Comment by dongsikkim** [comment]
I have same problem, but i can't find solution. this is very weired. it is happen only android api 25.
