### ISSUE TITLE
Fatal Exception: java.lang.ClassCastException: com.daimajia.slider.library.Tricks.FinitePagerAdapter cannot be cast to com.daimajia.slider.library.Tricks.InfinitePagerAdapter

### ISSUE THREAD

**Issue by tootsweet** [daimajia/AndroidImageSlider#335]
**Occurred on:**
- Android 6: 49%
- Android 5: 32%
- Android 7: 12%
- Android 4: 7%

**Full stack trace:**
Fatal Exception: java.lang.ClassCastException: com.daimajia.slider.library.Tricks.FinitePagerAdapter cannot be cast to com.daimajia.slider.library.Tricks.InfinitePagerAdapter
       at com.daimajia.slider.library.Tricks.ViewPagerEx.triggerOnPageChangeEvent(ViewPagerEx.java:311)
       at com.daimajia.slider.library.Tricks.ViewPagerEx.setCurrentItemInternal(ViewPagerEx.java:559)
       at com.daimajia.slider.library.Tricks.ViewPagerEx.setCurrentItemInternal(ViewPagerEx.java:526)
       at com.daimajia.slider.library.Tricks.ViewPagerEx.setCurrentItem(ViewPagerEx.java:518)
       at com.daimajia.slider.library.SliderLayout.moveNextPosition(SliderLayout.java:692)
       at com.daimajia.slider.library.SliderLayout$2.handleMessage(SliderLayout.java:248)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6934)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by ShyamAg** [comment]
same here any update ?
